// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbilfcsemnqpukrzxnqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRiaWxmY3NlbW5xcHVrcnp4bnFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NDQ3ODcsImV4cCI6MjA3MDUyMDc4N30.RzYmrYHqZIxuAKTPhds3O4KoWQYeSB1dw4s6V7652gk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});